repos:
    remote-hetzner-boxes-personal:
        password: ENC[AES256_GCM,data:KASwoTl8S844NTYqjMH2x4DnhN7zpX49y4Kz,iv:EwZUCFfRQN65ry2K3Ralv0qtmsNc+BghPaelLerm060=,tag:V07Jw57ngIqBthkNVnLn1g==,type:str]
sops:
    age:
        - recipient: age1np3wdsudf9ruakyvgym48c0ygjs2f8uyshphlmswdta904h2f5zshr2rtr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5aWZNZHAvUGNpSStvaS9z
            azc4cVlJT3hVZU1FL3g2RGFmaEFmRWxoUEJRCk9pMzR3L3hXWWxUa2w1S1NwL2FJ
            aVBVYmhFTkVZQkhDRFZlZmVKVnhiVjgKLS0tIFJhZ1phdTBHYnBUNkdIZkR2ZFk1
            c2E1d3JxMWUranRBcmhiUzVhUG40WkkKD36RCWtdOnz/2oWGeQz7+VxVgEc376jv
            sAtHpcd32ww/YYQbHpnU6Ozsh23p1jTHwWcK3y5GndT8mXIQIT/GYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-29T06:30:35Z"
    mac: ENC[AES256_GCM,data:SE8IR3rs1Mk4zcjwTEDY95nNLoqD5oMyIfWhwQLPsKX8z4nNdJFJDMdwOlQv2aphTtzeb9/B9KVLUs4+RHTDff8yZd/50Cj4mr2et2O6vf2P9zAmlaHHeaFWpRtZmlVHhziTmZa7SL7CWOnR6c16pPSvQB5y09Sz8XtZVfLWiBA=,iv:4u1Mig+7XLam+r9BF/wcStDfAvHsBj2DthfEgsFfUy4=,tag:JhV+4D6WgSRs4WcrHNLJoA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
