dns:
    foodogsquared.one:
        rfc2136-key: ENC[AES256_GCM,data:49GrRg1btqzohxarjeCa+lCRDEkAeC/cmTkkN7Ukt5pVM5cCu78ctGpGdZ56ey/HC5DEjpEbT9rLpUncD6ZfcpbGi8q/mQuLjIifsVAsFTO3/N/d8iBvKLQyoMkER/evYQiKUqqb08M81koZxuTX9mY11nh795kSrZM=,iv:Bb1R3PkMC0CNeeds6pJzf9FN6SHtBbDhjhI7w657qsk=,tag:O91Xd595ftDtlK3jmYVA4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yftkhugwrdnlpl45lthrhvvk720zza2nd085sxvjcxg2guavz3kquktplx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNXRmbXB6YWJxa0w1R3Rh
            ZzVjMHNtdStETXkraEhrbVVIQWtRT1FEbWcwCiszSmFTR2s4RUI1SlJWL3RMTHN2
            a1Qva1Z5TC9PU3hSd2xHczdaZkdnelEKLS0tIE1kQ2FhV3hOY3lHbEx1SUlLSi9X
            NHY2MWtSZEtKUkdJa1dnT0VhQWN1dUUKbi24Rv2vAT5teHt9dKltJyKjLpLDuYDw
            SxoVKJ6zgEnkwhByAQwHKwwd6fSgPicl2b0kNGUJrooHlwHEUqsDMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-29T04:30:53Z"
    mac: ENC[AES256_GCM,data:VLfdVNGmcGMR2DhqeFr25DM6tweODdpUg1S2dX3Ci7bVPHIqa3ErpwEpItOhEpLs87T1A5W++963o30WCzwdNFX4uEUj9iFnA+F+DFSjQ8zn7BH+Zql1/EHjBWXGprOWB2uYcSn6INZUO9TAmgU+fF6QVOGcPjjalukA5+jLWWc=,iv:GP55tYc5/TbOHrimd9AETu/4MpaTinWR69pD9FSUyM4=,tag:kRFNuMiY2dScBHkoK67WjA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
