keys:
  - &foo-dogsquared 7C7F9DC0694508015FE4C9F2DD5E7C08041214EE
  - &foo-dogsquared-old 8FCE86932583783E515B6FE55F2B001E20ED3763
  - &foo-dogsquared-old-2 DDD7D0BD602E564BAA04FC3514310D9141152B92
  - &foo-dogsquared-age age1np3wdsudf9ruakyvgym48c0ygjs2f8uyshphlmswdta904h2f5zshr2rtr
  - &ni age12uu6hgy44pvt2rawjgl2m8vdfcn820hxxlmkmgumfyeewswh29tq9asn94
  - &plover age1yftkhugwrdnlpl45lthrhvvk720zza2nd085sxvjcxg2guavz3kquktplx
creation_rules:
  - path_regex: configs/nixos/ni/(modules/.+/(.+\.)?secrets|secrets/[^/]+)\.(yaml|json|ini|env|bin)$
    age: *ni
  - path_regex: configs/nixos/plover/(modules/.+/(.+\.)?secrets|secrets/[^/]+)\.(yaml|json|ini|env|bin)$
    age: *plover
  - path_regex: configs/home-manager/foo-dogsquared/(modules/.+/(.+\.)?secrets|secrets/[^/]+)\.(yaml|json|ini|env|bin)$
    age: *foo-dogsquared-age
