# This is project data for deploying home-manager users with this flake. Each
# of the users defined here should correspond to one of the home-manager users
# at `./users/home-manager/`.
[foodogsquared]
system = "x86_64-linux"

[plover]
system = "x86_64-linux"
