secrets-config: ENC[AES256_GCM,data:DuOZXDbxX+ODhY/9P+bGBMVdl/OXKvv64WpncryJRR7cjYoOJtNKb6TrzUkZoCaO6kGdbZRhv0/EDkPwbyIsEWVcjGPAI14r3Wl1nly8pSnSpEuMUVAGQuix3zAnSw60WPlDuILZLNsneAB5,iv:LFt1959lDZn1xo4VMjX9O95BJ6rSUMwiXY/aHzzTrQU=,tag:UJFAJJ4pggSfbKNkzroudw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dm9xugju4q5gx0zty8ckw655ea904c64gv9qw9fn3lu507ck8uzsag59y8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZHFUS2FjOTFNTGpza3FG
            TVVzN3lDRXhYNVowM3R4b3lVd2MzejZEamhZClVPMnRsbjcyckRrd1E0SkJoRTlV
            bHZBVjJmbGJkMnEyV1YvdnFqQnAzb1kKLS0tIElCNFZzcGNRWFk0a3FVa3MyaG8w
            TmoyL2wySVV6SWZ4ZjNTYVlTbmd6Z28Kot16Blm1wLrqUz3O3Y/0/9f6yA+9Lt8X
            npo0Sw4yRDpU4tKwulpOQbbUEnnYTtWeB7kgBjQC+5Bn11otW1FKzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-20T08:16:17Z"
    mac: ENC[AES256_GCM,data:KOCuxHeg4VEcuzF5SWVRx5ahWAvFb+eGOyTvv5sNgA9JE7ectven0REXMM+2Qytn9+UmVVFRH4SSV89YB0BI2x2+GL+hLuLYIRCJ1/s4p9B+LIRfz6rqeo/w0ETHT+b2JjRhC99igHwksD+bLnHQo9XFcNvT2gDxvOaX+mSurSQ=,iv:+zrR7lSHLEhgtNR3/IMSnzBFoE59NJ/CzuoVz/KdauI=,tag:H59qLT3SLo4yYrzJexTryA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
