# SPDX-FileCopyrightText: 2024-2026 Gabriel Arazas <foodogsquared@foodogsquared.one>
#
# SPDX-License-Identifier: MIT

.PHONY: build
build:
	hugo --destination public

.PHONY: serve
serve:
	hugo serve
