# SPDX-FileCopyrightText: 2024-2026 Gabriel Arazas <foodogsquared@foodogsquared.one>
#
# SPDX-License-Identifier: MIT

# frozen_string_literal: true

source 'https://rubygems.org'
gem 'asciidoctor'
gem 'asciidoctor-diagram'
gem 'asciidoctor-foodogsquared-extensions'
gem 'concurrent-ruby'
gem 'open-uri-cached'
gem 'rouge'
gem 'slim'
gem 'tilt'
gem 'base64'
gem 'logger'
gem 'ostruct'

group :development do
  gem 'rake'
  gem 'ruby-lsp', require: false
end

group :lint do
  gem 'rubocop', require: false
end
