# SPDX-FileCopyrightText: 2023-2026 Gabriel Arazas <foodogsquared@foodogsquared.one>
#
# SPDX-License-Identifier: MIT

source 'https://rubygems.org'

gemspec

group :development do
  gem 'rake'
  gem 'ruby-lsp', require: false
end

group :lint do
  gem 'rubocop', require: false
end
