penpot:
    env: ENC[AES256_GCM,data:DXBNMffXGqLNWuKspjIk/HpcfYmjgegSrG9o7BGEC7LRn5lWzPJ91BJbI6RMMMOuzbYTcc2ce31DT05STeHUQjJEi8Wa2kHJa3VEuInuonC1tpMuNfVf4tiqj5zfCcUTErCNaA6uyHvUnWWMORDemiWvLk8vBdo5NaeHnxnknz0edes6Vb2xoW9u5G/KKGgKDJtCiEmdM+i59SfRxNdxx1yeZRb6RjGrBBe46+eHln7VY6DgE7T6P8eMB+C+T9wtwv5puAuIj8I9448PziKL7gem3pQpTdopHS8wAo11dXY6tC1qKDfJOaeOgsMJyS6I0UQi9zgip933mVCFcGdJDJGlZcofn199xoqWONmJknt0P2ofdtVrVyl159I6GgN0DgJUBhJ5UjjvfjngzOTjHlAwIdY2t2d1ymz2MIZxy+AkRdUaWmbJS+6TQT49Mf2p/knQEjUbl3fx2B3rOepHy9w=,iv:5WOOdu23e32EfTM2y1CgZH06Fqt+2+S64SnbX21YN54=,tag:VfjDuqE7G6lDPCusQrB6yQ==,type:str]
    postgres_env: ENC[AES256_GCM,data:BYTV62cRPNpRVOVD4vH2wLsftW9vm7JaabCJhFzpAR7BMIq4lOWkKZ34fl6CBA4wYcPIc+hFsbYNZa2hpy3NXJY=,iv:+LRpFbX4rQkCJtGUnjlqAoIKVpTengRsBKKHKtIo4E4=,tag:IoHQw9/MciJVgSQnZI1NRA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jxna9vm7nx4g69s84qgjptxvuzszcypf2rfk4ss2lyhnpe3yxdnqusu6jp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQ21La1p3R3pYbkI0Mkl2
            N0d5ekwvQkdLWFlSSFZlNzZEek5rSUpXQlM0Cld4bUd1MCtIRm9pZDRQVll2eWhE
            NkdGTmcrS1pqZndXMzFMTUlhbGwwQ3MKLS0tIGVENTRpVmMxbW5CL2FRbFhBd3pV
            VHAyQStoallxZXkwcWt3Y2VPeVZiWXMKvsGVPPFHYeTmpqyY63MI6aaDdvWC3OEE
            ONka99YLasKLNkGqdEptDMTmo66nQ66pz0BG+NZuwoxkjJzvViektw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T04:07:10Z"
    mac: ENC[AES256_GCM,data:QvNwoudxSs/I9Mi38Dgw5o8n3sMkqTLPfnKluUq+Qt08BVXf7G/lNgjQpUSVyB8CljsslR4+zeZ7SDt1QNtOzEgnl7IkYKRCN7rBlwuJNETfaVMHZ37P9WLo7DGmwS5+GTxaYa8XH1SokCTmlcRF8P6urCTLuaL6eUWaEVaYiOo=,iv:kXpwc1LKHl0I4hvLMdPHfjsZJc74Y4qUTH2a5gcGt1U=,tag:kwgr0qkx7PAkhhZKNHV41A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
