miniflux:
    admin: ENC[AES256_GCM,data:qHW2/5YXgIU2tHw7sa0wO97vM+PCMP6cmBc89Mp/pwtThBV1p/yECzdE4GS4YXp0AsAptFAg0TkUpQ==,iv:yvVaSo6sieLgXdAKK8iAMzuyL3ctHIvczWZPXx4to1M=,tag:V7cS2Ku4APT3GXiQw77/Mg==,type:str]
sops:
    age:
        - recipient: age12uu6hgy44pvt2rawjgl2m8vdfcn820hxxlmkmgumfyeewswh29tq9asn94
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTDUvRktJU0RIVmFDMXE1
            VTRudE5YY0cxWFNwczhRWDRWd2dkSDFZRTI4CmJZR0c0VTNleSsxclI2eU93MHNu
            YTVwNWFJcUdvZVdyMGowY1BDV0xEQ2sKLS0tIGlidEc4TmxsemhoQlVNSjRTYjNX
            VHgzQUVsZHNFOTdCNnQ2TmhIRmM3M3cKYSNZ5p5G786R++H1GfFJ05Ru1ZiPv9Fv
            G8+MuBMl77g/wX7sQ8ZMVIvNbxvWlOsbE3CDCjatrM7C1RUx3Nkd0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-29T05:12:16Z"
    mac: ENC[AES256_GCM,data:SYVlX/sjA6vk5rFGraD2P6i2wLkUQi4gSGrCGtLx9RxSg830P4C/vZdiQUStpCqQVwpcbACY5158V4pkV2sVOBZqb7hflYkN7xknCF+pCUbOom/Wtlm9Vi3cN6Su45o5nufG0xkbb4ywm0FFEx6mh6w2Jg1GKuoudd/tbACpOAQ=,iv:8h/PO4Udl1MXdDfw+TvA8Z1+CcMRLVpSABkwoQ88YSQ=,tag:eehZAAt7SYNH/H5UQJdccg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
