miniflux:
    admin: ENC[AES256_GCM,data:N332Q6cocCp3HrVO0AnjM26Rwq1X2vr1R+NzlcECF6blDcaVFkXzOobBNR4+iDHT09B+MNDO7YIg,iv:xwTMf1x+3tPLUlcYhJlD0P8aSTOIOIRe4cW79m5JiZs=,tag:UkeQPwS8D2ClTgUP5g9aUg==,type:str]
sops:
    age:
        - recipient: age12uu6hgy44pvt2rawjgl2m8vdfcn820hxxlmkmgumfyeewswh29tq9asn94
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTDUvRktJU0RIVmFDMXE1
            VTRudE5YY0cxWFNwczhRWDRWd2dkSDFZRTI4CmJZR0c0VTNleSsxclI2eU93MHNu
            YTVwNWFJcUdvZVdyMGowY1BDV0xEQ2sKLS0tIGlidEc4TmxsemhoQlVNSjRTYjNX
            VHgzQUVsZHNFOTdCNnQ2TmhIRmM3M3cKYSNZ5p5G786R++H1GfFJ05Ru1ZiPv9Fv
            G8+MuBMl77g/wX7sQ8ZMVIvNbxvWlOsbE3CDCjatrM7C1RUx3Nkd0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-30T05:00:46Z"
    mac: ENC[AES256_GCM,data:mSWykp52ZJvJh2QcS2QDjnm43vSApc6L5SsZI+tf6niaSq2eStyCy88Eyb1zIfxcm4dpk+6Ier1apIn6N4iJUy6EWQjTdLoBb1OKZsHHWsJMa0bbgBFLVH0Q1akmTeEdjnirpWqP7dhvAcscYzXSSqERd6oahkpAV32wWq8adnU=,iv:piElIeUm4Puxia6BgJZaTw5I+gHbPcV25matKMPtlmE=,tag:IIAMPFXysJhiY67DE8f9ug==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
