miniflux:
    admin: ENC[AES256_GCM,data:TMDKcG9rp1tA+FLEgogpH7e3sFUKAKOKyFe9o2g7It/nELNroLDRgh6kgbRsqIEqeeAzENi9yR27bg==,iv:pwHRAmLSR1oDwH8wzS+tFQikocNmjrYWeS3H9M/9pzc=,tag:VRiEWHb17dcMiTDPOh7vqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jxna9vm7nx4g69s84qgjptxvuzszcypf2rfk4ss2lyhnpe3yxdnqusu6jp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWjd2TC95NFQ4VXBheVlP
            TDUwajluNHhsY1ZPSlYxMlN1L25EZzhjQjBrCnFjWmI2WUZXNER0dkF6dVlNSUVs
            MUcwNmFpODZmdHUvY1VlSEdtOTNqRFkKLS0tIHhkK3BWSXFTZS9DcHRPNG9hbzN5
            bG5tektneTBvR29yTzVqNHZVYldKZXMKWgRWcu0kl6TwIeDTU1N4ofH1HY+G9/zh
            GrppMajmw5ZLB3/e3xCzn4KaAEUkcLvJjq9AgZzjQm/PXhzlAxU4tg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-31T08:27:39Z"
    mac: ENC[AES256_GCM,data:/j7QFv8cuKL2TXEmtVgx9qxMqpBOJydOQmzbNOCY8ZxSIvB/lstmGk7Q4lByb51H6KBiSDdJFewXmQo+hosafOMX7cAY4rQvzD5zEylmntESMOKnEdG39zo0HKAcLDapUSsPjEj0L/BGqhyU6ZKAJgFrEwq9aWGS9NKHXvhMD+Q=,iv:BeURmnqEfro8JcRZ0CQ269D/UinK3jAeSVQavGCbODw=,tag:BLEnDVX3fxEP/KCsOVGO3Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
