patterns:
    keys: ENC[AES256_GCM,data:XwibSHDoFQB/CjdJY0Z085IxRG+WYlvmGJPa7bB1wvRNaru9xv0qBhdPVmh8ZufpL2+ATVq3DOdb05YQtTysQLaDYxAIe3OhyqS39EwxH0BLpJAkBcI=,iv:3pnChOuSSKivk3CyJP9ZiiWvBn4vzRNzbodjA0dpwQM=,tag:Q9o7dLCwdJ7UKB7uXJRI6w==,type:str]
repos:
    external-hdd:
        password: ENC[AES256_GCM,data:hTJ+uvLFwyzpHW7ogARaL1vEdXGzdvHivHTeseb7fw==,iv:Qm8GyQulUJUXTrKFBSKbafZ31fcMQBCOZ/nyexXkgjU=,tag:vpMv3VQO/v3gFZjQ1uIneQ==,type:str]
sops:
    age:
        - recipient: age12uu6hgy44pvt2rawjgl2m8vdfcn820hxxlmkmgumfyeewswh29tq9asn94
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVS3c0bmgvK0t1dXFTNG4x
            elZ6Yzg3bmxHU0hIVmxvQjJMS2Z0bmx3M3k0ClI1TTdvdXkxTUVoK29xL2huREYz
            VTBnZ2RxSWs5MWViTUZDampnZi84RXMKLS0tIDRKRGpLWDJJTDlVRXNLWU5oLzRm
            TWxOckJLeXI1UENiU0VwR2pNeEdxazQK8R3JUpQFyEX9FP+37GENwmbQfQj4RODf
            hDjIPHEnNVaKX0EES4VsxG90i2DcZmVU/Dwdytc+p6H18uKip/RDCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T13:25:36Z"
    mac: ENC[AES256_GCM,data:AMSXhpPyEArxu/valDWgtvXtJlg1lJpOvxNs1D6IUKnP9O0db/MVzlgOFoFSC4cfXBHLEh4OigKWNj+Fbqv86GNWhHV712Lp7sSUzyqRVOtQNaNgLypiJteSE0GAM2H1huhGosfyeCVZSzdaQBpbowKJUa+0l0aKeA+sa4iL7zc=,iv:8gChI+kZo+sz4zukPXbg9Hrw0ZkDaQzfj5Z/e1uHiqI=,tag:iwXFvXvzR1yCppB3iNw6mw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
