patterns:
    home: ENC[AES256_GCM,data:FQyVpxe+3MAwoE/d4sb1ZmD/2Y8rBEQEd+qsTAzvY+Hi2ANiHERN4tuwPbHY8zK67yIFlEsnMEDngYzOkH2mas1aJf1hf3w+yEB6IIh+IhYApzWivQADumj6rPVJT2WfItlz2S9Z8+LFzD48xPnN3UboJ1vicMZeSm/Ffp342CQzG6lQlmMpoQCy4Q5bNPk8Kk8YOnFMhMuq+/jgtIMnl27WYiVpYzM6kSrq96J8VxAS4XJMHIWP/bzk+CrE7tsdhNgnS+JzuLRhERwB+sKJ5m2TBNVC31ZOSJeROYXCus0CDyaGEoy7ssDfAfBjePqAGzTMKxayLoMh4GbIPTmqLyfsl9IWXLRFiDBnbPYVgCSdxgINye4mEg==,iv:0+1etWOkvmngX3KPUCxYpIJ5QoUjEw8RtAM8XH6bEu4=,tag:R0e+thbJAro/ZFnFvf13IA==,type:str]
    keys: ENC[AES256_GCM,data:xxuamNHPWLpQyERawROxaRdUek6HoDypPK9zw9WGRJthk+7vtCWhyZLLndz0j0ST0H5mU9L9rwDJ4GiyKvPgAyk4iP4=,iv:FclOzefSaDDc+VXq/EMdKX95GfzInPvdKdaBqkNTQRI=,tag:p/0upm4ef/ESx0m9MUPROg==,type:str]
    root: ENC[AES256_GCM,data:mHDo6whty2eiz8ZRhM3bpJ2fPNx5KMzkG0+J/E/CfR7EG02yY3y2Xu+fYQ==,iv:iX9tqqR5Qqbk8uyDczLpotOw68Aj2glpp/ZcOvQ+NQo=,tag:Ni2rcy4UK0HUOVuET5AwwQ==,type:str]
repos:
    archives:
        password: ENC[AES256_GCM,data:FuPW5dgbt20+eOT4ulV653amUocILnSgc2sBYaeusXw=,iv:WZJYpYdWQzs8G23P4Zflhlxe/H1tShPvMjmFEiLHl4A=,tag:lZUC9JBIwhcEiBpPajaKUw==,type:str]
    hetzner-box:
        password: ENC[AES256_GCM,data:GuNsNiVGHyUPrkVMlUQfAEIs/1bGfp3qYseXi/T+lQ==,iv:qrTs+T89R8wzvCxKzYoJyVzBGMczIDqhqfXB93pyxBU=,tag:KdO2cQjMjkJviBF+/5wzdA==,type:str]
        ssh-key: ENC[AES256_GCM,data:b6A6ryV8gtBLWs0zje6KmTGvsMCDjS7KkisctZYkQ6Mt+1V5r49mVkgsZJF4zemK0FENR1usBeOQW9ylkmZD4attYrIp20KgMs7lmehpViE3xk8MA/m6TFUjR0bXh/FW+bwQ2JPFh09kmEmvPsj0gbGXp6Ine63PxQOPc2wZxxkgm1hjnDFeZVhknw5L3UrmvsOD2ex6lrCip6LwsKcz+9v4KRixQJkAQreALQ8lyw32FYKB8GwPsTSDjGpqiQAZWq1u8jEZcPmITW60qVH42V4jD0tny0HkQIaY5TpssPWbNrB1DPyKTtq1ZyRWRcTVtGQAGLcmcA2+vErdGDuM0YbvJmSbzRIj3EE9dR9gQJ19N1LRoJnQn2qLE5TovYFFa4V7tTx8GMa34dUmHfaIhotk+itCL/le9dhROdb2W1FabpRM7NkObJKdyV9HR88WpAZFr9wpnuOyEKW2qFFVqsPpmHP21VkKfbGJxm3LL6zw4MHN/WsFvfMF2NQCshOXixubQNiDaEQcMjlx3tS7easuB3Lavg3vQa4F,iv:hV4FupMtLb8lpe3JWlkbFLBu37kae06InNiZTOlppo0=,tag:k1rVBDz4mjD1ovxiTSEtZA==,type:str]
    external-hdd:
        password: ENC[AES256_GCM,data:P9LNQIs456JBWFJs1ARQHLiNeLWlkhPWaEgX431VYg5YNA==,iv:cN3v9jMZlHRVUHdhvXnDizl0GdpVlw5U70yYlxAv3ek=,tag:mYaq2M8xSBfl5+lAa1NNVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jxna9vm7nx4g69s84qgjptxvuzszcypf2rfk4ss2lyhnpe3yxdnqusu6jp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVExxY094cElKaG9KVUVC
            R0R1RXd6YjViRnlpM2VKaDY3NlNUZXpoSEcwCithUUhzbERveVlRZm40bzQ0bitH
            OEh4MlRLNjdsQjYvNENZMk5DMytoMjAKLS0tIHV6NkdYUGN3d1RpNmFxTWY4YW1s
            emJQY1B4UHQvVDJxQlVlUjZXcW5hV2MKAqRYMFGWoXALeUeDoFCYFvCT8pIIRGk4
            xMZwLHvRWuZW+15DYGrfrA9+DOS6SZYEYQeApMFVWUdYMU/Xn6KZig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-11T01:00:45Z"
    mac: ENC[AES256_GCM,data:uvK0SmRAF/9xLrc5iF7GJBi0SbNKZ2U2Dudai6owToknCqiU5N0w9JudY7+eTxtD/RZkB2h2Kvq1aMEpbahdl8zZ4F6o7vxs1oeNcXAuB1gHGOfpG8AI+gojUrKZP5SKWsCqUOTjRtxAR9AjG0pR/rhbJjJ8EbQ9UawsaqQHMFk=,iv:VYSmLqDsViLwSJ1qsmjLFmlchJfM7QMmAD6HYC7jaWQ=,tag:hLGh+qdJsRXquXhWbnikUw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
