name: "Check flake outputs"
on: [pull_request, push]
env:
  NIXPKGS_ALLOW_INSECURE: "1"
  NIXPKGS_ALLOW_BROKEN: "1"
  NIXPKGS_ALLOW_UNFREE: "1"
jobs:
  check-outputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            keep-going = true
      - name: Check flake outputs
        run: nix flake check --impure

