name: "Check flake outputs"
on: [pull_request, push]
env:
  NIXPKGS_ALLOW_UNFREE: "1"
jobs:
  check-outputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - uses: DeterminateSystems/nix-installer-action@v4
      - name: Check flake outputs
        run: nix flake check --impure
