name: "Build personalized bootstrap ISO"
on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - docs/
jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - uses: DeterminateSystems/nix-installer-action@v4
      - name: Build ISO
        run: |
          nix build .#images.bootstrap --out-link build-iso-result
      - name: Create release
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create latest --prerelease --generate-notes build-iso-result/iso/*.iso
